
CREATE TABLE traffic_violations (
    id INT AUTO_INCREMENT PRIMARY KEY,
    PlateNumber VARCHAR(20),
    DriverName VARCHAR(100),
    Description TEXT,
    Belts VARCHAR(10),
    Personal_Injury VARCHAR(10),
    Property_Damage VARCHAR(10),
    Commercial_License VARCHAR(10),
    Commercial_Vehicle VARCHAR(10),
    State VARCHAR(10),
    VehicleType VARCHAR(50),
    Year INT,
    Make VARCHAR(50),
    Model VARCHAR(50),
    Color VARCHAR(20),
    Charge VARCHAR(50),
    PenaltyAmount DECIMAL(10,2),
    Contributed_To_Accident VARCHAR(10),
    Race VARCHAR(50),
    Gender VARCHAR(10),
    Driver_City VARCHAR(100),
    Driver_State VARCHAR(10),
    DL_State VARCHAR(10),
    Arrest_Type VARCHAR(50),
    Violation_Type VARCHAR(50)
);
INSERT INTO traffic_violations 
(PlateNumber, DriverName, Description, Belts, Personal_Injury, Property_Damage, Commercial_License, Commercial_Vehicle, State, VehicleType, Year, Make, Model, Color, Charge, PenaltyAmount, Contributed_To_Accident, Race, Gender, Driver_City, Driver_State, DL_State, Arrest_Type, Violation_Type) 
VALUES
('ABC1234','Driver_1','DISPLAYING EXPIRED REGISTRATION PLATE ISSUED BY STATE','No','No','No','No','No','NC','Automobile',2013,'HYUNDAI','ELANTRA','GRAY','13411f',2500,'No','WHITE','F','ASHEVILLE','NC','NC','A - Marked Patrol','Citation'),
('ABC5678','Driver_2','DRIVER FAIL TO STOP AT RED TRAFFIC SIGNAL','No','No','No','No','No','MD','Automobile',2015,'FORD','FOCUS','SILVER','21202i1',1800,'No','OTHER','M','SILVER SPRING','MD','MD','A - Marked Patrol','Citation'),
('ABC9012','Driver_3','DRIVING UNDER THE INFLUENCE OF ALCOHOL PER SE','No','No','No','No','No','MD','Automobile',2000,'TOYOTA','COROLLA','BLACK','21902a2',3200,'No','BLACK','M','SILVER SPRING','MD','MD','B - Unmarked Patrol','Citation'),
('ABC4321','Driver_4','PERSON DRIVING MOTOR VEHICLE WITHOUT LICENSE','No','No','No','No','No','MD','Automobile',2012,'HONDA','CIVIC','BLACK','16303c',4000,'No','BLACK','M','COLUMBIA','MD','MD','A - Marked Patrol','Citation'),
('ABC8765','Driver_5','DISPLAYING EXPIRED REGISTRATION PLATE','No','No','No','Yes','No','MD','Automobile',2010,'FORD','ESCAPE','BLACK','13411f',2100,'No','WHITE','M','MOUNT AIRY','MD','MD','A - Marked Patrol','Citation'),
('ABC1357','Driver_6','FAILURE TO YIELD RIGHT OF WAY','No','No','Yes','No','No','MD','Automobile',2008,'NISSAN','ALTIMA','RED','20802b',3600,'No','ASIAN','F','ROCKVILLE','MD','MD','A - Marked Patrol','Citation'),
('ABC2468','Driver_7','DRIVING WITHOUT PROPER EQUIPMENT','No','No','No','No','No','VA','Automobile',2009,'CHEVROLET','MALIBU','WHITE','14503d',1400,'No','HISPANIC','M','FAIRFAX','VA','VA','C - State Trooper','Citation'),
('ABC3690','Driver_8','FAILURE TO STOP AT STOP SIGN','No','No','No','No','No','DC','Automobile',2011,'KIA','RIO','BLUE','20501e',2700,'No','WHITE','F','WASHINGTON','DC','DC','A - Marked Patrol','Citation'),
('ABC1122','Driver_9','EXCEEDING SPEED LIMIT BY 20 MPH','No','No','Yes','No','No','MD','Automobile',2017,'HYUNDAI','SONATA','GRAY','22005f',3300,'Yes','BLACK','M','BALTIMORE','MD','MD','B - Unmarked Patrol','Citation'),
('ABC3344','Driver_10','IMPROPER LANE CHANGE','No','No','No','No','No','MD','Automobile',2014,'FORD','FUSION','WHITE','19807g',1500,'No','WHITE','F','SILVER SPRING','MD','MD','A - Marked Patrol','Citation'),
('ABC5566','Driver_11','DRIVING WITHOUT HEADLIGHTS AT NIGHT','No','No','No','No','No','NC','Automobile',2005,'TOYOTA','CAMRY','BLACK','13009h',2800,'No','ASIAN','M','CHARLOTTE','NC','NC','C - State Trooper','Citation'),
('ABC7788','Driver_12','FAILURE TO SIGNAL WHILE TURNING','No','No','No','No','No','MD','Automobile',2006,'HONDA','ACCORD','BLUE','20904i',1600,'No','WHITE','F','GAITHERSBURG','MD','MD','A - Marked Patrol','Citation'),
('ABC9900','Driver_13','DRIVING UNDER THE INFLUENCE','No','Yes','Yes','No','No','MD','Automobile',2003,'CHEVROLET','IMPALA','RED','21905j',4800,'Yes','BLACK','M','BALTIMORE','MD','MD','B - Unmarked Patrol','Citation'),
('ABC2233','Driver_14','OPERATING UNREGISTERED VEHICLE','No','No','No','Yes','No','MD','Automobile',2001,'FORD','FOCUS','WHITE','13411f',1200,'No','HISPANIC','M','ROCKVILLE','MD','MD','A - Marked Patrol','Citation'),
('ABC4455','Driver_15','FAILURE TO OBEY TRAFFIC CONTROL DEVICE','No','No','No','No','No','VA','Automobile',2016,'NISSAN','SENTRA','BLACK','21202i1',1900,'No','WHITE','F','ARLINGTON','VA','VA','C - State Trooper','Citation'),
('ABC6677','Driver_16','IMPROPER TURN AT INTERSECTION','No','No','No','No','No','DC','Automobile',2007,'HYUNDAI','ELANTRA','SILVER','20907k',1750,'No','OTHER','M','WASHINGTON','DC','DC','A - Marked Patrol','Citation'),
('ABC8899','Driver_17','DRIVING WITHOUT SEATBELT','Yes','No','No','No','No','MD','Automobile',2018,'FORD','ESCAPE','BLUE','15008l',1000,'No','BLACK','M','SILVER SPRING','MD','MD','A - Marked Patrol','Citation'),
('ABC1212','Driver_18','FAILURE TO MAINTAIN SAFE DISTANCE','No','No','Yes','No','No','MD','Automobile',2012,'TOYOTA','PRIUS','GREEN','20004m',2600,'Yes','ASIAN','F','BETHESDA','MD','MD','B - Unmarked Patrol','Citation'),
('ABC3434','Driver_19','IMPROPER BACKING OF VEHICLE','No','No','Yes','No','No','MD','Automobile',2010,'HONDA','CIVIC','BLACK','20705n',2300,'No','WHITE','F','COLUMBIA','MD','MD','A - Marked Patrol','Citation'),
('ABC5656','Driver_20','FAILURE TO STOP FOR SCHOOL BUS','No','No','No','No','No','VA','Automobile',2015,'NISSAN','ALTIMA','WHITE','22106o',4200,'No','HISPANIC','M','FAIRFAX','VA','VA','C - State Trooper','Citation'),
('ABC7878','Driver_21','OPERATING VEHICLE WITH SUSPENDED LICENSE','No','No','No','No','No','MD','Automobile',2004,'TOYOTA','COROLLA','RED','13411p',3500,'No','BLACK','M','BALTIMORE','MD','MD','B - Unmarked Patrol','Citation'),
('ABC9090','Driver_22','DRIVING WITHOUT INSURANCE','No','No','No','No','No','MD','Automobile',2002,'FORD','TAURUS','BLUE','14009q',2950,'No','WHITE','F','ROCKVILLE','MD','MD','A - Marked Patrol','Citation'),
('ABC1414','Driver_23','DRIVING WITHOUT VALID REGISTRATION','No','No','No','No','No','MD','Automobile',2013,'HYUNDAI','SONATA','BLACK','13411f',1100,'No','ASIAN','M','SILVER SPRING','MD','MD','A - Marked Patrol','Citation'),
('ABC3636','Driver_24','FAILURE TO YIELD TO PEDESTRIAN','No','No','Yes','No','No','DC','Automobile',2016,'HONDA','CIVIC','GRAY','20802r',2850,'Yes','WHITE','F','WASHINGTON','DC','DC','A - Marked Patrol','Citation'),
('ABC5858','Driver_25','SPEEDING IN SCHOOL ZONE','No','No','No','No','No','MD','Automobile',2019,'FORD','FOCUS','WHITE','22005s',3900,'No','BLACK','M','GAITHERSBURG','MD','MD','C - State Trooper','Citation');

